<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="styles.css">
    <title>Home</title>
</head>
<body>
    <?php
        include "templates/banner.php";
    ?>
    <div id="help-container">
        <div id="help-info">
            <h2>How to Use the Memory Game Web Application</h2>
            <p>The Memory Game has been designed as a convenient, fun, and user friendly web application
                with the aim of enhancing cognitive functions of populations vulnerable to cognitive decline.
                The rules are simple: A series of buttons will light up in a random sequence. The player must
                click the buttons in the same sequence. The number of "moves" will increase to the limit selected
                by the player. The number of buttons in the game will be chosen by the player. To increase the
                difficulty of the game, increase the number of buttons and the number of moves generated by 
                the machine.
            </p>
        </div>
        <div id="help-faq">
            <h2>Frequently Asked Questions</h2><br>
            <p>Q: How do I set my name?</p><br>
            <p>A: To set a name, the player enters their name in the settings menu on the home page before preceding to the game page.</p><br>
            <p>Q: How do I adjust the number of buttons or moves?</p><br>
            <p>A: To adjust the number of buttons or moves, the player must enter the desired number on the home page before launching the game.</p><br>
            <p>Q: I entered a number in the buttons or moves settings, and the actual number in the game was different. Why?</p><br>
            <p>A: The number of buttons or moves a player may set is limited. You may have 4-8 buttons and 5-30 moves.</p><br>
        </div>
    </div>
    <?php
        include "templates/footer.php";
    ?>
</body>
</html>